name: Checkout and install ruby
description: Basic setup for all workflows
runs:
  using: "composite"
  steps:
    - name: Install ruby
      uses: ruby/setup-ruby@78c01b705fd9d5ad960d432d3a0cfa341d50e410 # v1.179.1
      with:
        ruby-version: '3.3'
